// This component was generated by @sitecore-search/cli on Thu Mar 20 2025 11:27:02 GMT+0530 (India Standard Time)

import type { SearchResponseAnswer } from "@sitecore-search/react";
import { WidgetDataType, useQuestions, widget } from "@sitecore-search/react";
import { useState, useRef, useEffect } from "react";
import { MessageSquare, Send, X, ChevronRight, Sparkles } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

type Message = {
  type: "user" | "bot";
  content: string;
};

export const SearchChatbotComponent = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [suggestedQuestions, setSuggestedQuestions] = useState<
    SearchResponseAnswer[]
  >([]);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  const toggleChat = () => {
    setIsOpen(!isOpen);
    if (!isOpen && messages.length === 0) {
      // Add welcome message when opening for the first time
      setMessages([
        {
          type: "bot",
          content: "Hello! How can I help you today?",
        },
      ]);
    }
  };

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
    if (isOpen && inputRef.current) {
      inputRef.current.focus();
    }
  }, [messages, isOpen]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim()) return;

    const userMessage = input;
    setInput("");

    // Add user message to chat
    setMessages((prev) => [...prev, { type: "user", content: userMessage }]);
    onKeyphraseChanged({
      keyphrase: userMessage,
    });
  };

  const handleSuggestedQuestionClick = (question: SearchResponseAnswer) => {
    // Add the question to the chat as if the user asked it
    setMessages((prev) => [
      ...prev,
      { type: "user", content: question.question },
    ]);
    // Add the answer
    setMessages((prev) => [...prev, { type: "bot", content: question.answer }]);
    // Clear suggested questions
    setSuggestedQuestions([]);
  };

  // Bubble animation variants
  const bubbleVariants = {
    initial: { scale: 0 },
    animate: {
      scale: 1,
      transition: { type: "spring", stiffness: 260, damping: 20 },
    },
    exit: { scale: 0, opacity: 0 },
  };

  // Message animation variants
  const messageVariants = {
    initial: { opacity: 0, y: 10 },
    animate: { opacity: 1, y: 0, transition: { duration: 0.3 } },
    exit: { opacity: 0, y: -10, transition: { duration: 0.2 } },
  };
  const {
    actions: { onKeyphraseChanged },
    queryResult: { isLoading, isFetching, data },
  } = useQuestions({
    state: {
      relatedQuestions: 3,
    },
    query: (query) => {
      query.getRequest().getQuestionsExactAnswer();
    },
  });
  useEffect(() => {
    if (!(isLoading || isFetching) && data?.related_questions) {
      setSuggestedQuestions(data?.related_questions);
    }
  }, [data?.related_questions]);

  useEffect(() => {
    if (!(isLoading || isFetching) && data?.answer?.answer) {
      // Add the answer
      setMessages((prev) => [
        ...prev,
        { type: "bot", content: data?.answer?.answer as string },
      ]);
      // Clear suggested questions
      setSuggestedQuestions([]);
    }
  }, [data?.answer]);
  return (
    <>
      {/* Chat toggle button with animated effects */}
      <motion.button
        aria-label={isOpen ? "Close chat" : "Open chat"}
        onClick={toggleChat}
        className="fixed bottom-6 right-6 w-16 h-16 rounded-full bg-gradient-to-r from-purple-600 to-pink-600 text-white flex items-center justify-center shadow-lg hover:shadow-xl focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500 z-50"
        whileHover={{ scale: 1.1, rotate: 5 }}
        whileTap={{ scale: 0.95 }}
        initial={{ y: 100 }}
        animate={{
          y: 0,
          transition: { type: "spring", stiffness: 200, damping: 20 },
        }}
      >
        <AnimatePresence mode="wait">
          {isOpen ? (
            <motion.div
              key="close"
              initial={{ rotate: 180, opacity: 0 }}
              animate={{ rotate: 0, opacity: 1 }}
              exit={{ rotate: -180, opacity: 0 }}
              transition={{ duration: 0.3 }}
            >
              <X size={28} />
            </motion.div>
          ) : (
            <motion.div
              key="open"
              initial={{ rotate: -180, opacity: 0 }}
              animate={{ rotate: 0, opacity: 1 }}
              exit={{ rotate: 180, opacity: 0 }}
              transition={{ duration: 0.3 }}
            >
              <MessageSquare size={28} />
            </motion.div>
          )}
        </AnimatePresence>
      </motion.button>

      {/* Animated bubbles around the button when closed */}
      <AnimatePresence>
        {!isOpen && (
          <>
            <motion.div
              initial={{ scale: 0, x: 0, y: 0 }}
              animate={{
                scale: [0, 1, 1, 0],
                x: [0, -30, -40, -50],
                y: [0, -20, -30, -40],
              }}
              transition={{
                duration: 3,
                repeat: Number.POSITIVE_INFINITY,
                repeatType: "loop",
                times: [0, 0.3, 0.7, 1],
                delay: 1,
              }}
              className="fixed bottom-14 right-14 w-3 h-3 rounded-full bg-purple-400 opacity-70 z-40"
            />
            <motion.div
              initial={{ scale: 0, x: 0, y: 0 }}
              animate={{
                scale: [0, 1, 1, 0],
                x: [0, 20, 30, 40],
                y: [0, -30, -40, -50],
              }}
              transition={{
                duration: 4,
                repeat: Number.POSITIVE_INFINITY,
                repeatType: "loop",
                times: [0, 0.3, 0.7, 1],
                delay: 0.5,
              }}
              className="fixed bottom-14 right-14 w-4 h-4 rounded-full bg-pink-400 opacity-70 z-40"
            />
            <motion.div
              initial={{ scale: 0, x: 0, y: 0 }}
              animate={{
                scale: [0, 1, 1, 0],
                x: [0, -10, -15, -20],
                y: [0, -40, -50, -60],
              }}
              transition={{
                duration: 3.5,
                repeat: Number.POSITIVE_INFINITY,
                repeatType: "loop",
                times: [0, 0.3, 0.7, 1],
                delay: 2,
              }}
              className="fixed bottom-14 right-14 w-2 h-2 rounded-full bg-cyan-400 opacity-70 z-40"
            />
          </>
        )}
      </AnimatePresence>

      {/* Chat window */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, y: 20, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 20, scale: 0.95 }}
            transition={{ type: "spring", stiffness: 300, damping: 25 }}
            className="fixed bottom-24 right-6 w-96 h-[500px] bg-white rounded-2xl shadow-2xl flex flex-col overflow-hidden z-40 border border-purple-200"
            role="dialog"
            aria-modal="true"
            aria-labelledby="chat-title"
          >
            {/* Chat header with gradient */}
            <div className="bg-gradient-to-r from-purple-600 to-pink-600 text-white p-4 flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <Sparkles className="h-5 w-5 text-yellow-300" />
                <h2 id="chat-title" className="font-bold text-lg">
                  Sitecore Search Chat bot
                </h2>
              </div>
              <button
                onClick={toggleChat}
                aria-label="Close chat"
                className="text-white hover:text-gray-200 focus:outline-none focus:ring-2 focus:ring-white rounded"
              >
                <X size={20} />
              </button>
            </div>

            {/* Chat messages with enhanced animations */}
            <div className="flex-1 overflow-y-auto p-4 space-y-4 bg-gradient-to-b from-purple-50 to-white">
              <AnimatePresence>
                {messages.map((message, index) => (
                  <motion.div
                    key={index}
                    variants={messageVariants}
                    initial="initial"
                    animate="animate"
                    exit="exit"
                    className={`flex ${
                      message.type === "user" ? "justify-end" : "justify-start"
                    }`}
                  >
                    <motion.div
                      variants={bubbleVariants}
                      className={`max-w-[80%] p-3 rounded-2xl shadow-sm ${
                        message.type === "user"
                          ? "bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-br-none"
                          : "bg-white border border-purple-100 text-gray-800 rounded-bl-none"
                      }`}
                    >
                      {message.content}
                    </motion.div>
                  </motion.div>
                ))}
                {(isLoading || isFetching) && (
                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="flex justify-start"
                  >
                    <div className="bg-white border border-purple-100 p-4 rounded-2xl rounded-bl-none max-w-[80%] shadow-sm">
                      <div className="flex space-x-2">
                        <motion.div
                          className="w-3 h-3 rounded-full bg-purple-600"
                          animate={{ y: [0, -10, 0] }}
                          transition={{
                            duration: 1,
                            repeat: Number.POSITIVE_INFINITY,
                            ease: "easeInOut",
                            times: [0, 0.5, 1],
                            delay: 0,
                          }}
                        />
                        <motion.div
                          className="w-3 h-3 rounded-full bg-fuchsia-500"
                          animate={{ y: [0, -10, 0] }}
                          transition={{
                            duration: 1,
                            repeat: Number.POSITIVE_INFINITY,
                            ease: "easeInOut",
                            times: [0, 0.5, 1],
                            delay: 0.2,
                          }}
                        />
                        <motion.div
                          className="w-3 h-3 rounded-full bg-pink-500"
                          animate={{ y: [0, -10, 0] }}
                          transition={{
                            duration: 1,
                            repeat: Number.POSITIVE_INFINITY,
                            ease: "easeInOut",
                            times: [0, 0.5, 1],
                            delay: 0.4,
                          }}
                        />
                      </div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
              <div ref={messagesEndRef} />
            </div>

            {/* Suggested questions with enhanced styling */}
            <AnimatePresence>
              {suggestedQuestions.length > 0 && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: "auto" }}
                  exit={{ opacity: 0, height: 0 }}
                  className="px-4 py-3 bg-gradient-to-r from-purple-50 to-pink-50 border-t border-purple-100"
                >
                  <p className="text-sm text-gray-600 mb-2 font-medium">
                    Suggested questions:
                  </p>
                  <div className="space-y-2">
                    {suggestedQuestions.map((q) => (
                      <motion.button
                        key={q?.document_id}
                        onClick={() => handleSuggestedQuestionClick(q)}
                        className="w-full text-left p-2.5 rounded-xl bg-white border border-purple-200 hover:border-purple-300 hover:bg-purple-50 focus:outline-none focus:ring-2 focus:ring-purple-500 text-sm flex items-center shadow-sm transition-all duration-200"
                        whileHover={{ scale: 1.02, x: 5 }}
                        whileTap={{ scale: 0.98 }}
                      >
                        <span className="flex-1 truncate text-gray-700">
                          {q.question}
                        </span>
                        <ChevronRight size={16} className="text-purple-400" />
                      </motion.button>
                    ))}
                  </div>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Chat input with enhanced styling */}
            <form
              onSubmit={handleSubmit}
              className="p-4 border-t border-purple-100 bg-white"
            >
              <div className="flex items-center space-x-2">
                <input
                  ref={inputRef}
                  type="text"
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  placeholder="Type your question..."
                  className="flex-1 p-3 border border-purple-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all duration-200"
                  aria-label="Type your message"
                  disabled={isLoading}
                />
                <motion.button
                  type="submit"
                  className="p-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-xl disabled:opacity-50 shadow-md hover:shadow-lg transition-all duration-200"
                  disabled={!input.trim() || isLoading}
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  aria-label="Send message"
                >
                  <Send size={20} />
                </motion.button>
              </div>
            </form>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
};
const SearchChatbotWidget = widget(
  SearchChatbotComponent,
  WidgetDataType.QUESTIONS,
  "content"
);
export default SearchChatbotWidget;
